//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackoverflow.SqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public Answer()
        {
            this.CommentaryAnswer = new HashSet<CommentaryAnswer>();
        }
    
        public long Id { get; set; }
        public long UserId { get; set; }
        public long QuestionId { get; set; }
        public int Usefulness { get; set; }
        public string Body { get; set; }
        public System.DateTime PublicationDate { get; set; }
        public bool BestAnswer { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual User User { get; set; }
        public virtual ICollection<CommentaryAnswer> CommentaryAnswer { get; set; }
    }
}
