//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackoverflow.SqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommentaryAnswer
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public long AnswerId { get; set; }
        public string Body { get; set; }
        public System.DateTime PublicationDate { get; set; }
    
        public virtual Answer Answer { get; set; }
        public virtual User User { get; set; }
    }
}
