//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stackoverflow.SqlContext.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Answer = new HashSet<Answer>();
            this.CommentaryAnswer = new HashSet<CommentaryAnswer>();
            this.CommentaryQuestion = new HashSet<CommentaryQuestion>();
            this.Question = new HashSet<Question>();
        }
    
        public long Id { get; set; }
        public string Nickname { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Sex { get; set; }
        public System.DateTime BirthDate { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
    
        public virtual ICollection<Answer> Answer { get; set; }
        public virtual ICollection<CommentaryAnswer> CommentaryAnswer { get; set; }
        public virtual ICollection<CommentaryQuestion> CommentaryQuestion { get; set; }
        public virtual ICollection<Question> Question { get; set; }
    }
}
